# 配置tomcat端口号
server:
  port: 8080

# 配置数据源
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxx_db
    username: root
    password: root

# 配置日志
logging:
  config: classpath:log4j2-spring.xml